version: '3'

networks:
  wpnet:
    name: wpnet
volumes:
  DB_data:


services:

  wp-web:
    #image: wordperss:latest
    build:
      context: ./conf/dockerfiles
      dockerfile: Dockerfile.wp
    hostname: wordperss
    ports:
      - ${IP}:${PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - wp-db
    networks:
      - wpnet
    volumes:
      - /sym/disk1/appdata/minilatte2:/var/www/html # /sym/disk1/... is a symlink.
    restart: unless-stopped
  
  wp-db:
    image: mariadb
    hostname: database
    # ports:
    #   - ${IP}:${DBPORT}:3306
    networks:
      - wpnet
    # command: [
    #      '--default_authentication_plugin=MARIADB_native_password',
    #      '--character-set-server=utf8mb4',
    #      '--collation-server=utf8mb4_unicode_ci'
    #  ]
    volumes:
      - /sym/disk1/appdata/testwebdb:/var/lib/MARIADB
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: user
      MARIADB_ALLOW_EMPTY_PASSWORD: true
 
  wp-pma:
      image: phpmyadmin/phpmyadmin
      hostname: pma
      environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
       PMA_HOST: database
       PMA_PORT: 3306
      ports:
       - ${IP}:${PMAPORT}:80
      restart: unless-stopped
      networks:
        - wpnet
