version: '3'

networks:
volumes:
  wp-web:
  wp-db:

services:
  wp-web:
    #image: wordperss:latest
    build:
      context: ./conf/dockerfiles
      dockerfile: Dockerfile.wp
    hostname: wordperss
    ports:
      - 192.168.0.50:${PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: cmoison
    depends_on:
      - wp-db
    volumes:
      - /sym/disk1/appdata/minilatte:/var/www/html # /sym/disk1/... is a symlink.
    restart: unless-stopped
  
  wp-db:
    image: mariadb
    hostname: database
    volumes:
      - /sym/disk1/appdata/minilattedb:/var/lib/MARIADB
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: cmoison
      MARIADB_PASSWORD: cmoison
      MARIADB_USER: admin
      MARIADB_ALLOW_EMPTY_PASSWORD: true
